### ISSUE TITLE
Define permissions per access levels

### ISSUE THREAD

**Issue by poorgeek** [nwheeler/terebinth#2]
I need to grant Terebinth access to a non-Super User. For other components, I'd have to set a new Access Level, allow that level access Terebinth, and then assign my user to the new level. However, Terebinth doesn't allow for permissions to be granted to any other access levels.

Would like to see an Options view created with access to setting the Permissions by existing Access Levels.

**Comment by poorgeek** [comment]
Need to look into this soon.

/cc @pkaplan

**Comment by nwheeler** [comment]
I've added support for permissions (not via access levels). Just go to "Options" under Components->Terebinth and you'll see the available permissions-related settings. Unfortunately, there seems to be an error in teh automatic update process for Joomla 2.x. To install, please first uninstall the old plugin and install the new one! Thanks!
